name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main

env:
  PAGES_PROJECT_NAME: cloudflare-pages-deploy-action

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
      - name: Report coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: unit

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Production
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        uses: ./
        with:
          account-id: '${{ secrets.CF_ACCOUNT_ID }}'
          api-key: '${{ secrets.CF_GLOBAL_APIKEY }}'
          email: '${{ secrets.CF_EMAIL }}'
          project-name: '${{ env.PAGES_PROJECT_NAME }}'
          production: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test Preview
        if: ${{ github.event_name == 'pull_request' }}
        uses: ./
        with:
          account-id: '${{ secrets.CF_ACCOUNT_ID }}'
          api-key: '${{ secrets.CF_GLOBAL_APIKEY }}'
          email: '${{ secrets.CF_EMAIL }}'
          project-name: '${{ env.PAGES_PROJECT_NAME }}'
          preview: true
          # branch: ${{ github.head_ref }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
